In [15]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer as si

In [16]:
d=pd.read_csv("googleplaystore.csv")

In [17]:
impute=si(missing_values=np.nan,strategy="mean")
impute.fit(d.iloc[:,2:3].values)
d.iloc[:,2:3]=impute.transform(d.iloc[:,2:3].values)

In [18]:
d=d.dropna()
d.head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up

In [28]:
d1=d[d["Category"]=="FAMILY"]
d1=d1[d1["Rating"]>4.5]
x=d1[d1["Type"]=="Free"].values

In [40]:
d.sort_values(by = "Rating",ascending=False)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
7291,CG Prints,PHOTOGRAPHY,5.0,1,2.3M,100+,Free,0,Everyone,Photography,"January 24, 2017",1.0.5,4.3 and up
5763,Tozer Devotional -Series 1,BOOKS_AND_REFERENCE,5.0,5,4.3M,"1,000+",Free,0,Everyone,Books & Reference,"October 8, 2016",1.0,2.3 and up
10611,"Beacon Baptist Jupiter, FL",LIFESTYLE,5.0,14,2.6M,100+,Free,0,Everyone,Lifestyle,"October 13, 2017",2.4,4.0.3 and up
6391,BK Arogyam Task Track,BUSINESS,5.0,8,3.7M,100+,Free,0,Everyone,Business,"June 5, 2018",1.1.1,4.1 and up
6396,Bk Usha behn,LIFESTYLE,5.0,10,3.0M,"1,000+",Free,0,Everyone,Lifestyle,"January 14, 2018",1.0,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8820,DS Creator 2.0,TOOLS,1.0,2,4.4M,500+,Free,0,Everyone,Tools,"March 23, 2018",2.0.180226.1,4.0 and up
10591,Lottery Ticket Checker - Florida Results & Lotto,TOOLS,1.0,3,41M,500+,Free,0,Everyone,Tools,"December 12, 2017",1.0,4.2 and up
7144,CB Mobile Biz,FINANCE,1.0,3,8.4M,500+,Free,0,Everyone,Finance,"February 22, 2016",4.4.1255,4.0 and up
7806,CR Magazine,BUSINESS,1.0,1,7.8M,100+,Free,0,Everyone,Business,"July 23, 2014",2.4.2,2.3.3 and up
7926,Tech CU Card Manager,FINANCE,1.0,2,7.2M,"1,000+",Free,0,Everyone,Finance,"July 25, 2017",1.0.1,4.0 and up

In [43]:
d=d[d["Type"]=="Paid"]
d.groupby("Category").count()["Type"].sort_values(ascending=False).head()

Category
FAMILY             190
MEDICAL            109
GAME                83
PERSONALIZATION     82
TOOLS               77
Name: Type, dtype: int64

In [47]:
d1.groupby(d1.index)

In [59]:
d.aggregate({"Rating":len,})

Rating    797
dtype: int64